name: Master

on:
  push:
    branches:
      - master
      - "[0-9].[0-9].x"

jobs:
  Test:
    # Ignore release commits
    if: "!startsWith(github.event.head_commit.message, 'Release')"

    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js 12.16.1
        uses: actions/setup-node@v1
        with:
          node-version: 12.16.1

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm run bot

  Release:
    # Ignore release commits
    if: "!startsWith(github.event.head_commit.message, 'Release')"

    needs:
      - Test

    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v2
        with:
          # Use personal access token for cloning (and later pushing) code
          token: ${{ secrets.CI_TOKEN }}

      - name: Use Node.js 12.16.1
        uses: actions/setup-node@v1
        with:
          node-version: 12.16.1

      - name: Install dependencies
        run: npm ci

      - name: Trigger release
        run: npm run release
        env:
          # Use personal access token for creating releases on GitHub
          GITHUB_TOKEN: ${{ secrets.CI_TOKEN }}
