name: Action Test

on: [push]

jobs:
  check_user_permission:
    runs-on: ubuntu-latest
    name: A job to check user's permission level
    steps:
      # Check write permission
      - name: Check for write permission
        id: check-write
        uses: scherermichael/action-has-permission@master
        with:
          required-permission: "write"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Run only if user has sufficent permissions
        if: steps.check-write.outputs.has-permission
        run: echo "Congratulations! Your permissions to access the repository are sufficent."
      - name: Run only if user has NOT sufficent permissions
        if: "! steps.check-write.outputs.has-permission"
        run: echo "Sorry! Your permissions are insufficent."

      # Check superuser permission
      - name: Check for test-only-superuser permission
        id: check-superuser
        uses: scherermichael/action-has-permission@master
        with:
          required-permission: "test-only-superuser"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ADD_TEST_PERMISSION: true
      - name: Run only if user has sufficent permissions
        if: steps.check-superuser.outputs.has-permission
        run: echo "Congratulations! Your permissions to access the repository are sufficent."
      - name: Run only if user has NOT sufficent permissions
        if: "! steps.check-superuser.outputs.has-permission"
        run: echo "Sorry! Your permissions are insufficent."

      # Check default permission
      - name: Check for default permission
        id: check-default
        uses: scherermichael/action-has-permission@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Run only if user has sufficent permissions
        if: steps.check-default.outputs.has-permission
        run: echo "Congratulations! Your permissions to access the repository are sufficent."
      - name: Run only if user has NOT sufficent permissions
        if: "! steps.check-default.outputs.has-permission"
        run: echo "Sorry! Your permissions are insufficent."
